### ISSUE TITLE
Failed to compile with 1 errors

### ISSUE THREAD

**Issue by lamasfoker** [minimit/xtendui#25]
https://github.com/minimit/xtendui/blob/51219b86090a884ded7a1994151e908abc2ce9a8/src/core/toggle.js#L1264

During the build one error occour:

> `You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders`

I think it's fault of the line highlighted, if you replace `??` with `||` all go like a charm.

**Comment by minimit** [comment]
hey!
Update webpack encore because webpack 4 doesn't support the nullish syntax with `??`

https://github.com/minimit/xtendui-boilerplate

**Comment by lamasfoker** [comment]
Thank you, now all work as expected.
